### ISSUE TITLE
i have tried but in my python console log, get this error below:

### ISSUE THREAD

**Issue by alvianaufan** [nfacha/OpenAI-Gitlab-PR-Review#4]
[2023-11-26 22:25:49,540] ERROR in app: Exception on /webhook [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/openai-gitlab-pr-review/main.py", line 17, in webhook
    if payload["object_attributes"]["action"] != "open":
KeyError: 'action'

**Comment by nfacha** [comment]
What is the Gitlab event you are sending?
